version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: postgres_container
    environment:
      POSTGRES_USER: matos_admin
      POSTGRES_PASSWORD: matos_pass
      POSTGRES_DB: matosmetalfestdb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - matos_metal_fest

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin_container
    environment:
      PGADMIN_DEFAULT_EMAIL: matos@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin_matos
    ports:
      - "5050:80"
    depends_on:
      - postgres
    networks:
      - matos_metal_fest

volumes:
  postgres_data:

networks:
  matos_metal_fest:
