spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/matosmetalfestdb
    username: matos_admin
    password: matos_pass
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  liquibase:
    enabled: true
    change-log: classpath:/db/changelog/db.changelog-master.yaml
